# Generated by Django 4.1.5 on 2023-03-09 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000, null=True)),
                ('city', models.CharField(max_length=5000)),
                ('bio', models.TextField()),
                ('phone', models.CharField(max_length=15, null=True)),
                ('company', models.CharField(max_length=5000)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('photo', models.ImageField(null=True, upload_to='media/agents')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=5000)),
                ('town', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('floor_plan', models.ImageField(upload_to='media')),
                ('price', models.FloatField()),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('bungalow', 'Bungalow'), ('duplex', 'Duplex')], max_length=50)),
                ('year_of_build', models.DateField(blank=True, null=True)),
                ('contract_type', models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], max_length=50)),
                ('home_area', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('parking', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aler.agent')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(null=True, upload_to='media')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aler.property')),
            ],
        ),
    ]
