# Generated by Django 4.0.4 on 2022-11-14 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=5000)),
                ('town', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('floor_plan', models.FileField(upload_to='media')),
                ('price', models.FloatField()),
                ('property_type', models.CharField(max_length=50)),
                ('year_built', models.IntegerField()),
                ('contract_type', models.CharField(max_length=50)),
                ('home_area', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('parking', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=5000)),
                ('city', models.CharField(max_length=5000)),
                ('bio', models.TextField()),
                ('phone', models.IntegerField()),
                ('company', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Property_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('rating', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aler.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aler.user'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='media')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aler.property')),
            ],
        ),
    ]
