# Generated by Django 4.0.4 on 2022-11-15 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='property',
        ),
    ]
