# Generated by Django 4.1.5 on 2023-03-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='property',
            name='state',
        ),
        migrations.RemoveField(
            model_name='property',
            name='town',
        ),
        migrations.AddField(
            model_name='property',
            name='agent_mail',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='agent_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
