# Generated by Django 4.0.4 on 2022-11-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0002_remove_photo_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photos',
            field=models.TextField(),
        ),
    ]
