# Generated by Django 4.1.5 on 2023-03-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0002_remove_property_agent_remove_property_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='year_of_build',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
