# Generated by Django 4.1.5 on 2023-03-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0003_alter_property_year_of_build'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='floor_plan',
            new_name='hero_photo',
        ),
    ]
