# Generated by Django 4.0.4 on 2022-11-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0004_alter_photo_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photos',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
