# Generated by Django 4.1.5 on 2023-03-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0004_rename_floor_plan_property_hero_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='hero_photo',
        ),
    ]
