# Generated by Django 4.1.5 on 2023-03-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0005_remove_property_hero_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='hero_photo',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
