# Generated by Django 4.0.4 on 2022-11-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0005_alter_photo_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='parking',
            field=models.IntegerField(null=True),
        ),
    ]
