# Generated by Django 4.0.4 on 2022-11-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0007_agent_delete_photo_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/agents'),
        ),
    ]
