# Generated by Django 4.0.4 on 2022-11-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0008_agent_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='floor_plan',
            field=models.ImageField(upload_to='media'),
        ),
    ]
