# Generated by Django 4.0.4 on 2022-11-17 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0009_alter_property_floor_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(null=True, upload_to='media')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aler.property')),
            ],
        ),
    ]
