# Generated by Django 4.0.4 on 2022-11-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0010_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='property',
            new_name='prop',
        ),
    ]
