# Generated by Django 4.0.4 on 2022-11-18 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0011_rename_property_photo_prop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='property_review',
            name='email',
        ),
        migrations.RemoveField(
            model_name='property_review',
            name='rating',
        ),
    ]
