# Generated by Django 4.0.4 on 2022-11-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0013_alter_property_review_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_review',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
