# Generated by Django 4.0.4 on 2022-11-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0016_alter_property_review_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
