# Generated by Django 4.0.4 on 2022-11-19 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0017_agent_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='email',
        ),
    ]
