# Generated by Django 4.0.4 on 2022-11-21 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0020_alter_property_agent_alter_property_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aler.agent'),
        ),
    ]
