# Generated by Django 4.0.4 on 2022-11-21 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0024_alter_property_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='agent',
        ),
    ]
