# Generated by Django 4.0.4 on 2022-11-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0027_agent_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
