# Generated by Django 4.0.4 on 2022-11-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0028_alter_agent_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
