# Generated by Django 4.0.4 on 2022-11-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0029_alter_agent_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['created']},
        ),
    ]
