# Generated by Django 4.0.4 on 2022-11-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0030_alter_agent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['-created']},
        ),
    ]
