# Generated by Django 4.0.4 on 2022-12-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0031_alter_agent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
