# Generated by Django 4.0.4 on 2023-02-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0032_alter_agent_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='year_built',
            field=models.DateField(),
        ),
    ]
