# Generated by Django 4.0.4 on 2023-02-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0033_alter_property_year_built'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='year_built',
            field=models.DateField(blank=True, null=True),
        ),
    ]
