# Generated by Django 4.0.4 on 2023-02-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aler', '0034_alter_property_year_built'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='year_built',
        ),
        migrations.AddField(
            model_name='property',
            name='year_of_build',
            field=models.DateField(blank=True, null=True),
        ),
    ]
